name: build-and-bump
on:
  push:
    branches: [ "main" ]
    paths:
      - "app/**"
      - "helm/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image_tag: ${{ steps.settag.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Derive image tag
        id: settag
        run: echo "image_tag=sha-${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Derive lowercase owner
        id: setowner
        run: echo "owner_lc=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"

      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./app
          file: ./app/Dockerfile.kube
          push: true
          tags: |
            ghcr.io/${{ steps.setowner.outputs.owner_lc }}/demo-app:${{ steps.settag.outputs.image_tag }}

  bump:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Update image.tag in helm/values.yaml
        run: |
          NEW_TAG='${{ needs.build.outputs.image_tag }}'
          FILE='helm/values.yaml'
          # простой безопасный апдейт через yq
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          yq eval --inplace '.image.tag = env(NEW_TAG)' "$FILE"
          echo "Changed image.tag to: $NEW_TAG"
          git diff -- "$FILE"

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(ci): bump image.tag to ${{ needs.build.outputs.image_tag }}"
          title: "Bump image.tag to ${{ needs.build.outputs.image_tag }}"
          body: |
            Auto-generated PR: update `helm/values.yaml` to image tag `${{ needs.build.outputs.image_tag }}`.
            Merge this to trigger Argo CD sync.
          branch: ci/bump-image-${{ needs.build.outputs.image_tag }}
          base: main
          labels: ci, automated
          signoff: false
